global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets:
                - host.docker.internal:8301
                - host.docker.internal:8302
                - host.docker.internal:8303
                - host.docker.internal:8304
                - host.docker.internal:8305
                - host.docker.internal:8306
                - host.docker.internal:8307
                - host.docker.internal:8308
                - host.docker.internal:8309
      metrics_path: "/metrics/prometheus"
