version: "2"

services:
    tgbot:
        build:
            context: ./
            dockerfile: packages/tgbot/Dockerfile
        env_file:
            - .env
        restart: always
        environment:
            - NODE_ENV=production
    gw:
        build:
            context: ./
            dockerfile: packages/gw/Dockerfile
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        extra_hosts:
            - "host.docker.internal:host-gateway"
        network_mode: "host"
