version: "2"

services:
    tarantool:
        image: tarantool-kraken:2.10
        build:
            context: ./packages/tnt

        environment:
            TARANTOOL_USER_NAME: tnt
            TARANTOOL_USER_PASSWORD: tnt
            TARANTOOL_SLAB_ALLOC_ARENA: 0.1

        volumes:
            # - ./packages/tnt/app.lua:/opt/tarantool/app.lua
            - tarantool:/var/lib/tarantool

        command: ["tarantool", "app.lua"]

        ports:
            - "3300:3000"
            - "3301:3301"

volumes:
    tarantool:
        driver: "local"
