version: "2"

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - 9090:9090
        volumes:
            - ./packages/prometheus:/etc/prometheus
        network_mode: "host"
        depends_on:
          - gw
    grafana:
        env_file:
            - .env
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000
        restart: unless-stopped
        network_mode: "host"
        depends_on:
          - prometheus
          - gw
    tgbot:
        build:
            context: ./
            dockerfile: packages/tgbot/Dockerfile
        env_file:
            - .env
        restart: always
        environment:
            - NODE_ENV=production
    gw:
        build:
            context: ./
            dockerfile: packages/gw/Dockerfile
        restart: always
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        network_mode: "host"
